baseURL = 'http://example.org/'
languageCode = 'en-us'
theme = "anatole"

[params]
title = "Mark Houghton"
author = "Mark Houghton"
description = "Mobile Engineer, Consultant, PhD"
profilePicture = "images/profile.jpeg"
mainSections = []
# displayMode = "light"
disableThemeSwitcher = false
pygmentsCodeFences = true
pygmentsUseClasses = true
# doNotLoadAnimations = true # Animations are loaded by default

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/mark-r-houghton/"

# [[params.socialIcons]]
# icon = "fab fa-github"
# title = "Github"
# url = "https://github.com/markrhoughton"

[[params.socialIcons]]
icon = "fab fa-medium"
title = "Medium"
url = "https://medium.com/@markrhoughton3/about"

# [[params.socialIcons]]
# icon = "fab fa-twitter"
# title = "Twitter"
# url = "https://twitter.com/mhsindoni"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:houghton.dev@outlook.com"

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Blog"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Projects"
  weight = 300
  identifier = "portfolio"
  url = "/portfolio/"

  [[menu.main]]
  name = "About Me"
  weight = 400
  identifier = "about"
  url = "/about/"
